# Site settings
title: Sustayn
description: > # this means to ignore newlines until "baseurl:"
  Sustayn rescues great food from being thrown out and 
  connects it with good homes that want to eat it! 
  Sustayn your health, your planet, and your community
url: "http://sustayn.io"
baseurl: "https://sustayn.github.io"
logo: <div class="logo-container"><img src="/assets/images/sustayn-no-background.svg" class="logo-image"><span class="light white-text logo-text">sustayn</span></div>
paginate: 5
paginate_path: "blog/page:num/"
owner:
  email: jake@sustayn.io
  facebook:
    show: true
    name: "Sustayn"
    url: "https://fb.me/sustayn"
  instagram:
    show: true
    username: "sustaynablefood"
  twitter:
    show: true
    username: "sustaynablefood"
sass:
  sass_dir: _sass
  style: compressed
permalink: "/article/:title"
gems:
  - jekyll-paginate
  - github-pages
