# Site settings
title: Jake Dluhy
description: > # this means to ignore newlines until "baseurl:"
  Sustayn rescues great food from being thrown out and 
  connects it with good homes that want to eat it! 
  Sustayn your health, your planet, and your community
url: "http://jakedluhy.com"
baseurl: ""
logo: <div class="logo-container"><img src="/assets/images/jakedluhy-logo.svg" class="logo-image"><span class="logo-text">Jake Dluhy</span></div>
paginate: 5
paginate_path: "blog/page:num/"
owner:
  email: dluhy.jake@gmail.com
  facebook:
    show: true
    name: Jake Dluhy
    url: https://fb.me/jake.dluhy
  instagram:
    show: true
    username: Jkerzz
  twitter:
    show: true
    username: Jkerzz
  github:
    show: true
    username: JakeDluhy
  linkedin:
    show: true
    username: jakedluhy
sass:
  sass_dir: _sass
  style: compressed
permalink: "/article/:title"
plugins:
  - jekyll-paginate

